version: 1.2
workflows:
   - subclass: CWL
     name: autopotato-attack
     primaryDescriptorPath: /potato.cwl
     latestTagAsDefault: true
     publish: True
     testParameterFiles:
         - /test/dockstore.cwl.json

