version: 1.2
workflows:
   - subclass: CWL
     name: autopotato-attack
     primaryDescriptorPath: /potato.cwl
     authors:
       - name: persona
         role: Institute
         affiliation: UCSC
     publish: True
     testParameterFiles:
         - /test/dockstore.cwl.json

